import Header from "@/components/ui/Header";

export default function page() {
  return (
    <main className="bg-black">
      <Header />
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
      <p>fsd</p>
    </main>
  );
}
